package com.example.systemtrackingtransport.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.systemtrackingtransport.db.Vehicle;

import com.example.systemtrackingtransport.db.VehicleDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig vehicleDaoConfig;

    private final VehicleDao vehicleDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        vehicleDaoConfig = daoConfigMap.get(VehicleDao.class).clone();
        vehicleDaoConfig.initIdentityScope(type);

        vehicleDao = new VehicleDao(vehicleDaoConfig, this);

        registerDao(Vehicle.class, vehicleDao);
    }
    
    public void clear() {
        vehicleDaoConfig.clearIdentityScope();
    }

    public VehicleDao getVehicleDao() {
        return vehicleDao;
    }

}
