package com.example.systemtrackingtransport.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.systemtrackingtransport.db.Vehicle;
import com.example.systemtrackingtransport.db.Sedan;
import com.example.systemtrackingtransport.db.Wagon;
import com.example.systemtrackingtransport.db.Suv;

import com.example.systemtrackingtransport.db.VehicleDao;
import com.example.systemtrackingtransport.db.SedanDao;
import com.example.systemtrackingtransport.db.WagonDao;
import com.example.systemtrackingtransport.db.SuvDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig vehicleDaoConfig;
    private final DaoConfig sedanDaoConfig;
    private final DaoConfig wagonDaoConfig;
    private final DaoConfig suvDaoConfig;

    private final VehicleDao vehicleDao;
    private final SedanDao sedanDao;
    private final WagonDao wagonDao;
    private final SuvDao suvDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        vehicleDaoConfig = daoConfigMap.get(VehicleDao.class).clone();
        vehicleDaoConfig.initIdentityScope(type);

        sedanDaoConfig = daoConfigMap.get(SedanDao.class).clone();
        sedanDaoConfig.initIdentityScope(type);

        wagonDaoConfig = daoConfigMap.get(WagonDao.class).clone();
        wagonDaoConfig.initIdentityScope(type);

        suvDaoConfig = daoConfigMap.get(SuvDao.class).clone();
        suvDaoConfig.initIdentityScope(type);

        vehicleDao = new VehicleDao(vehicleDaoConfig, this);
        sedanDao = new SedanDao(sedanDaoConfig, this);
        wagonDao = new WagonDao(wagonDaoConfig, this);
        suvDao = new SuvDao(suvDaoConfig, this);

        registerDao(Vehicle.class, vehicleDao);
        registerDao(Sedan.class, sedanDao);
        registerDao(Wagon.class, wagonDao);
        registerDao(Suv.class, suvDao);
    }
    
    public void clear() {
        vehicleDaoConfig.clearIdentityScope();
        sedanDaoConfig.clearIdentityScope();
        wagonDaoConfig.clearIdentityScope();
        suvDaoConfig.clearIdentityScope();
    }

    public VehicleDao getVehicleDao() {
        return vehicleDao;
    }

    public SedanDao getSedanDao() {
        return sedanDao;
    }

    public WagonDao getWagonDao() {
        return wagonDao;
    }

    public SuvDao getSuvDao() {
        return suvDao;
    }

}
