package com.example.systemtrackingtransport.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "VEHICLE".
 */
@Entity
public class Vehicle {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String brand;

    @NotNull
    private String model;

    @NotNull
    private String year;

    @NotNull
    private String type;

    @Generated
    public Vehicle() {
    }

    public Vehicle(Long id) {
        this.id = id;
    }

    @Generated
    public Vehicle(Long id, String brand, String model, String year, String type) {
        this.id = id;
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getBrand() {
        return brand;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBrand(@NotNull String brand) {
        this.brand = brand;
    }

    @NotNull
    public String getModel() {
        return model;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setModel(@NotNull String model) {
        this.model = model;
    }

    @NotNull
    public String getYear() {
        return year;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setYear(@NotNull String year) {
        this.year = year;
    }

    @NotNull
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(@NotNull String type) {
        this.type = type;
    }

}
