package com.example.systemtrackingtransport.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VEHICLE".
*/
public class VehicleDao extends AbstractDao<Vehicle, Long> {

    public static final String TABLENAME = "VEHICLE";

    /**
     * Properties of entity Vehicle.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Brand = new Property(1, String.class, "brand", false, "BRAND");
        public final static Property Model = new Property(2, String.class, "model", false, "MODEL");
        public final static Property Year = new Property(3, String.class, "year", false, "YEAR");
        public final static Property Type = new Property(4, String.class, "type", false, "TYPE");
    }


    public VehicleDao(DaoConfig config) {
        super(config);
    }
    
    public VehicleDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VEHICLE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"BRAND\" TEXT NOT NULL ," + // 1: brand
                "\"MODEL\" TEXT NOT NULL ," + // 2: model
                "\"YEAR\" TEXT NOT NULL ," + // 3: year
                "\"TYPE\" TEXT NOT NULL );"); // 4: type
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VEHICLE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Vehicle entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBrand());
        stmt.bindString(3, entity.getModel());
        stmt.bindString(4, entity.getYear());
        stmt.bindString(5, entity.getType());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Vehicle entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getBrand());
        stmt.bindString(3, entity.getModel());
        stmt.bindString(4, entity.getYear());
        stmt.bindString(5, entity.getType());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Vehicle readEntity(Cursor cursor, int offset) {
        Vehicle entity = new Vehicle( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // brand
            cursor.getString(offset + 2), // model
            cursor.getString(offset + 3), // year
            cursor.getString(offset + 4) // type
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Vehicle entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBrand(cursor.getString(offset + 1));
        entity.setModel(cursor.getString(offset + 2));
        entity.setYear(cursor.getString(offset + 3));
        entity.setType(cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Vehicle entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Vehicle entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Vehicle entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
